### ISSUE TITLE
产品线是否支持权限管理

### ISSUE THREAD

**Issue by jeff2088** [zttheff/gops#2]
我们测试过程中发现产品线是公开的，我们组织有运维部门，研发部还有产品部门，希望能实现不同部门有各自的权限来管理，产品命名模块明，研发创建部署任务，大概是这样的流程。希望能快速回复，谢谢！

**Comment by zttheff** [comment]
正在开发独立的产品线管理功能,产品线权限也回随着下个版本更新, 持续更新中，期待持续关注。

**Comment by jeff2088** [comment]
好的，期待中......
