### ISSUE TITLE
contains an invalid type, it should be a string

### ISSUE THREAD

**Issue by thellangel** [zttheff/gops#6]
安装时出现如下错误，
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx.volumes contains an invalid type, it should be a string
services.jupiter.volumes contains an invalid type, it should be a string
services.jupiter.volumes contains an invalid type, it should be a string
services.mars.volumes contains an invalid type, it should be a string
services.mars.volumes contains an invalid type, it should be a string
services.nginx.volumes contains an invalid type, it should be a string
services.saturn.volumes contains an invalid type, it should be a string
services.saturn.volumes contains an invalid type, it should be a string
services.db.volumes contains an invalid type, it should be a string

**Comment by thellangel** [comment]
在docker-compose.yml文件第一行增加如下即可
version: '3.2'

**Comment by zttheff** [comment]
👍🏻
